-- 코드를 작성해주세요
SELECT ID, FISH_NAME, LENGTH
FROM FISH_INFO i
INNER JOIN FISH_NAME_INFO ni
ON i.FISH_TYPE = ni.FISH_TYPE
WHERE (i.FISH_TYPE, i.LENGTH) IN(
    SELECT f.FISH_TYPE, MAX(f.LENGTH)
    FROM FISH_INFO f
    GROUP BY f.FISH_TYPE
    )
ORDER BY ID;